In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d


array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
print(np.zeros((3, 3)))
print(np.ones((2, 4)))
print(np.eye(3))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))
print(np.random.rand(3, 2))
print(np.random.randn(3, 2))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.65583497 0.54527798]
 [0.60173961 0.52906183]
 [0.06270976 0.24655003]]
[[-1.25802729  1.61805904]
 [ 0.29233756 -1.26289439]
 [ 0.71465578 -1.10579308]]


In [9]:
print(np.random.randint(1, 20))

19


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)   
print(arr.ndim)    
print(arr.size)    
print(arr.dtype)  


(2, 3)
2
6
int64


In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)
print(np.sin(a))

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))
print(A @ B)


[5 7 9]
[ 4 10 18]
[0.84147098 0.90929743 0.14112001]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [13]:
arr = np.array([1, 2, 3, 4])
print(arr.sum())

print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.std())

10
2.5
4
1
1.118033988749895


In [15]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])

print(arr[1:4])
print(arr[::2])

1
[2 3 4]
[1 3 5]


In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0, 1])
print(arr[:, 1])
print(arr[1, :2])

2
[2 5]
[4 5]


In [19]:
arr = np.array([1, 2, 3, 4, 5,6,7,10])
mask = arr >3
print(arr[mask])

[ 4  5  6  7 10]


In [21]:
arr = np.arange(12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.concatenate((a, b)))

[1 2 3 4]


In [23]:
print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[1 2]
 [3 4]]
[1 2 3 4]
